language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: unit test
      script: gradle build
      branches:
        only:
        - server
    - stage: code scan
      script: gradle sonarqube
      branches:
        only:
        - client
